### ISSUE TITLE
You are already connected to this server!

### ISSUE THREAD

**Issue by ringo-chan** [GotoFinal/AutoIn#28] opened 2015-04-25 08:51 UTC
Players in my server are getting disconnected with "Time out" error **randomly**, and they can't join the server again as bungee said they were already connected to the server. 
I failed to reproduce that problem, but I raised a similar issue up. I hope the fix for this issue will also fix that random problem.

----

Testing environment: 

 - Bungee version: Build 1059
 - Spigot version: git-Spigot-550ebac-7019900 (MC: 1.8)
 - AutoIn version: 3.0-alpha.2

What steps will reproduce the problem?

1. Setup the bungeecord server with AutoIn, and 2 spigot server (one with AutoIn and Auth plugin, and one without any plugin).
2. Connect to bungeecord, which will automagically send me to the lobby server with AutoIn installed.
3. In the bungeecord console, /send the user to another server without AutoIn.
4. Type anything in game. (i.e. chat or command)
5. User get disconnected with "Time out" message, while in bungeecord, run /glist or /find can still found the user.
6. User got "You are already connected to this server!" while trying to connect to bungeecord again. The bungeecord server **must** be restarted in order to allow the user to connect again.

Expected result:
The user will not get disconnected with time out error.

----

Also, thank you very much for this plugin. Actually I made a similar plugin, but requires offline-mode user logging in with a different domain, so I am really interested with the method you used. Will you consider to open source?

**Comment by GotoFinal** [comment] 2015-04-25 10:20
Sorry, but I want keep that closed source.
Can you try add AutoIn to that second server (and configure sockets ofc)? and say if that solve this problem?

**Comment by ringo-chan** [comment] 2015-04-25 10:37
Yes, it solved the problem.

**Comment by GotoFinal** [comment] 2015-04-25 10:44
I will try check if that can be fixed without any problems, but it's better to use AutoIn on every server,

**Comment by ringo-chan** [comment] 2015-04-25 16:58
Thank you :)

**Comment by GotoFinal** [comment] 2015-05-10 21:08
Can't reproduce on -alpha.3 IDK if it is fixed or it just depend on some other stuff, but closed for now, create new issue if needed

**Closed by GotoFinal** 2015-05-10 21:08 UTC
Labels: bug
