### ISSUE TITLE
Bungee can't join me to other server

### ISSUE THREAD

**Issue by Granik24** [GotoFinal/AutoIn#31] opened 2015-05-04 22:10 UTC
Hello, I have this problem.
In latest version, I can't teleport to my other server. I have Bungee and Lobby on my VPS and BedWars on other hosting. In previous version everythink works great, but now, I can't teleport from lobby. No error in console (lobby and bungee) and no connection task in BedWars server. Any ideas please? Thanks.

**Comment by TheMolkaPL** [comment] 2015-05-05 07:38
Do you have installed AutoIn on every instance of your Bukkit server?

**Comment by Granik24** [comment] 2015-05-05 08:14
In previous  version only on Bungee and Lobby. I tried to install AutoIn to my server, but server will frreeze after display AutoIn Beta Message

**Comment by Granik24** [comment] 2015-05-05 08:34
Oh sorry, here is server log: http://pastebin.com/FEA9Spf4

**Comment by GotoFinal** [comment] 2015-05-05 09:05
about error from logs... try change "ReTryConnectSocketTime" to something bigger, like 3000, on every server and proxy, and then try start all servers and proxy again.

**Comment by Granik24** [comment] 2015-05-05 09:46
The problem is, that the Handler is opening its socket on IPv6, but all of the Client servers can't handle IPv6 only IPv4. Even though the handler have its host set on IPv4.

**Comment by GotoFinal** [comment] 2015-05-05 11:44
so... use numeric IP instead of host name?

**Comment by Granik24** [comment] 2015-05-05 11:45
We using numeric IP

**Comment by GotoFinal** [comment] 2015-05-05 11:58
so it should not use ipv6, hyym, paste configurations of AutoIn and logs from start (from all servers and proxy)

**Comment by Granik24** [comment] 2015-05-05 15:43
Okay, here is it.
Bungee: http://pastebin.com/r6Pdm8xK (log)
Bungee config: http://pastebin.com/zTtaxmNf
Lobby: http://pastebin.com/jTXkniyw
BW: http://pastebin.com/mQ2RNyPL

**Comment by Granik24** [comment] 2015-05-05 16:18
Oh, and configs:
Bungee: http://pastebin.com/xBWqtPyP
Lobby: http://pastebin.com/YBuPgwJb
BW: http://pastebin.com/HQVhtCUp

**Comment by GotoFinal** [comment] 2015-05-05 19:00
if you just have problems with connecting to other server by BungeePortals or other plugin, then yeach, it may not work now... I fixed that on my local version but I still need fix other problems.

If you have other problem... they really, I don't have idea what that can be. everything other seems to works.

**Comment by Granik24** [comment] 2015-05-05 19:58
Yea, it seems with 3.0-alpha.1 it works. Can you send me that version with BungeePortal fix?

**Comment by GotoFinal** [comment] 2015-05-05 20:05
it will be uploaded to spigot when I finish fixing other errors, currently I can't even compile it.
But version alpha-1 is still available on spigotmc.org, I didn't move it like other, because I knew that changes made in .2 may broke something that I didn't check, so I leave old version for sure.

**Comment by Granik24** [comment] 2015-05-06 05:20
Hmm, is there any config for bungee commands? I only deleted old configs and now on any server can't work any plugin with bungee support.

**Comment by Granik24** [comment] 2015-05-06 12:39
"Failed to connect to the server"
"Internal Exception: io.netty.handler.timeout.ReadTimeoutException"
Error if I trying to connect to my server.

**Comment by GotoFinal** [comment] 2015-05-10 21:11
*probably* fixed on alpha.3

**Comment by Granik24** [comment] 2015-05-11 15:05
I think, it still not works. Now players can't loggin to my server with AuthMe.

**Comment by GotoFinal** [comment] 2015-05-11 15:23
paste current logs and configuration...

**Comment by Granik24** [comment] 2015-05-11 16:22
Okay, now about a problem.
I joined to my lobby server, everythink cool. Some players joined to server, everythink cool. But after some minutes, it kicked me with some message "io.netty..." and in server log "Granik24 lost connection: Timed out"

Here is lobby log: http://pastebin.com/BYR63UAU
Lobby config is new with only setuped sockets.
Here is bungee log: http://pastebin.com/7vSZiVP3
Bugee config is same with lobby. Pure with seted sockets.

**Comment by GotoFinal** [comment] 2015-05-11 17:40
you can only try disable `NeedLoginToUseCommands` on proxy AutoIn, but... as long as I can't reproduce it on my server, I can't fix that.

**Comment by Granik24** [comment] 2015-05-11 17:45
How about taht lobby server timeout? I have original account and it disconnected me with that message. I'll try to reproduce it

**Comment by Granik24** [comment] 2015-05-11 17:59
Here: http://gyazo.com/512f164d082ba7aa5ff6a988e7c9a156 is disconnect message
And here: http://gyazo.com/7954a3b30adecd03c5d95690ca6940ed is some stats about my CPU

**Comment by GotoFinal** [comment] 2015-05-11 18:15
try with that disabled `NeedLoginToUseCommands` and like I said, I need step by step instruction how to reproduce this.

**Comment by Granik24** [comment] 2015-05-11 18:25
Yea! Now it seems it works. CPU usage is on 10% and everything working for this while

**Closed** 2015-06-04 13:46 UTC
Labels: bug, OutdatedVersion
